version: "1.0"
info:
  model: int-scaffold
packages:
- name: KMAT_LD_JUL3Project
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm/KMAT_LD_JUL3Project
  gitUsername: karthikbm
  gitBranch: main
- name: SalesforceRESTKMAT
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: TestAWSS3Connr
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: KMATWorkdayTest
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
